### ISSUE TITLE
Can not parse the class fields 

### ISSUE THREAD

**Issue by vladblaj** [link2aws/link2aws.github.io#16]
Hello,
If I use it in a CRA app without shebang-loader(loader which removes #!/usr/bin/env node) I will get the following error when importing it:
![image](https://user-images.githubusercontent.com/5721913/140817378-b5bb8867-b36a-4956-8c56-480e87ecea86.png)
If I use shebang-loader, I will get the following error: 
![image](https://user-images.githubusercontent.com/5721913/140817474-9658b41b-eace-4102-9fc7-1afa66ca16ee.png)

This is because babel does not know how to transpile class fields. Even if I add  ["@babel/plugin-proposal-class-properties"], to babel config, it still does not work. Do you know how I could import  and transpile it properly?

**Comment by fxkr** [comment]
Thank you for your bug report, and my apologies that you are experiencing these issues.

## shebang issue

In your opinion, is using using shebang-loader an acceptable workaround?

I believe there are two options:

1. Document the need to use shebang-loader, and how to do it. Downside: requires user to use additional plugin. However: installing the plugin is not hard.
2. Remove the shebang for the file. Downside: breaks the "single executable .js file" use case. However: could still use it as `node link2aws.js`, and might be able to retain the easy CLI access by offering a separate `link2aws` binary that uses the library.

Since neither one of the approaches seems clearly better than the other, I could be easily convinced one way or another. If you have an opinion, please let me know.

## class fields issue

When I wrote the original code, apparently I mistakenly thought that class properties were already in the standard. The only good solution is to not rely on class properties. I intend to develop a fix and release a new version with it tonight.

There is actually a loader that would fix this, but a) it is experimental, and b) it only affects the project importing it, not its libraries, so using this is not a workaround for you.

## import of link2aws

Could you please share the line of code that you have used to import `link2aws.js` in your CRA? It appears to me that the way it currently is (code in `link2aws.js` and not `index.js`), import might actually fail. So I am surprised you did not mention this issue. I would like to come up with a fix for this, however I would like to be sure I can test it the way you did as well to ensure I will not break your app with any change that I make.

**Comment by fxkr** [comment]
I have published version 1.0.4 that contains the following fixes relevant for you:

1. No more experimental class properties syntax - you should not need plugin-proposal-class-properties now
2. No more shebang - you should not need shebang-loader now
3. Fixed import issue I mentioned

Can you please comment if everything works for you now?

Thank you!

**Comment by vladblaj** [comment]
Thank you very much for the quick reply. Everything works as intended without the need of additional babel plugins.
As for the import, with the current version it works like this:
`import { ARN } from "link2aws/link2aws.js";`
Maybe adding an index.js would make the import prettier.

**Comment by fxkr** [comment]
That was the import issue I mentioned and should already be fixed in that release (by setting `"main": "link2aws.js"` in `package.json` instead of creating `index.js` - for whatever reason the field was referring to a non-existing file. #10).

Did you try `import { ARN } from "link2aws"` with that new release? I created a test CRA and it works there.

**Comment by vladblaj** [comment]
It works! Thank you for your help and for the quick response.
All the best,
Vlad
